[build]
  command = "pnpm db:generate && if [ \"${RUN_DB_MIGRATIONS:-false}\" = \"true\" ] && [ -n \"$NETLIFY_DATABASE_URL\" ]; then export PRISMA_MIGRATION_ENGINE_ADVISORY_LOCK_TIMEOUT=${PRISMA_MIGRATION_ENGINE_ADVISORY_LOCK_TIMEOUT:-300000}; export NETLIFY_DATABASE_URL=${NETLIFY_DATABASE_URL_UNPOOLED:-$NETLIFY_DATABASE_URL}; pnpm tsx scripts/prisma-init-persistence.ts && bash ./scripts/prisma-deploy-retry.sh && pnpm db:seed; else echo 'Skipping Prisma migrate/seed'; fi && pnpm lint && pnpm typecheck && pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.19.5"
  SECRETS_SCAN_OMIT_KEYS = "UPLOADS_PROVIDER,REALTIME_TRANSPORT"
  PRISMA_MIGRATION_ENGINE_ADVISORY_LOCK_TIMEOUT = "300000"
  SENTRY_SKIP_OPEN_TELEMETRY_INSTRUMENTATION = "1"
  PNPM_FLAGS = "--no-frozen-lockfile"
  NPM_FLAGS = "--no-frozen-lockfile"
  RUN_DB_MIGRATIONS = "false"
  RUN_E2E = "false"

[context.deploy-preview]
  command = "pnpm db:generate && echo 'Skipping Prisma migrate/seed in deploy-preview' && pnpm lint && pnpm typecheck && pnpm build"
  [context.deploy-preview.environment]
  RUN_E2E = "false"

[context.branch-deploy]
  command = "pnpm db:generate && echo 'Skipping Prisma migrate/seed in branch-deploy' && pnpm lint && pnpm typecheck && pnpm build"
  [context.branch-deploy.environment]
  RUN_E2E = "false"

[dev]
  command = "pnpm dev"
  port = 3000

[context.production.environment]
  RUN_E2E = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# E2E plugin disabled
# [[plugins]]
#   package = "./netlify/plugins/run-e2e"

# Scheduled Functions
[[functions]]
  name = "cron-translation-metrics"
  schedule = "@daily"
  # Runs every day at midnight UTC (0 0 * * * in cron syntax)
